apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
spec:
  resources:
    data:
      limits:
        cpu: "5"
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 1Gi
    metrics:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 155m
        memory: 155Mi
